"use client";

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { useParams } from 'next/navigation';
import { toast } from 'sonner';
import { Activity, AlertTriangle, ArrowLeft, CalendarDays, CheckCircle2, Clock3, DollarSign, FileText, FolderKanban, GanttChart, Plus, Rocket, Settings2, Users } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Progress } from '@/components/ui/progress';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Textarea } from '@/components/ui/textarea';

type Task = { id: string; title: string; type: string; status: string; priority: string; startDate?: string; dueDate?: string; estimatedHours?: number; actualHours?: number; milestoneId?: string; sprintId?: string };
type Project = { id: string; name: string; code: string; description?: string; status: string; templateKey: string; visibility: string; version: number; budget?: number; currency: string; billingType: string; defaultBillingRate?: number; defaultCostRate?: number; tasks: Task[]; members: any[]; milestones: any[]; sprints: any[]; workflowStatuses: any[]; attachments: any[]; activities: any[]; billingBatches: any[]; timesheets: any[] };
type Resource = { id: string; role: string; allocationPct: number; openItems: number; estimatedHours: number; overloaded: boolean; user?: { name?: string; email?: string }; employee?: { firstName: string; lastName: string; position?: string } };
type Employee = { id: string; firstName: string; lastName: string; position?: string };

export default function ProjectWorkspacePage() {
  const { id } = useParams<{ id: string }>();
  const [project, setProject] = useState<Project | null>(null);
  const [resources, setResources] = useState<Resource[]>([]);
  const [employees, setEmployees] = useState<Employee[]>([]);
  const [sprintOpen, setSprintOpen] = useState(false);
  const [milestoneOpen, setMilestoneOpen] = useState(false);
  const [memberOpen, setMemberOpen] = useState(false);
  const [uploading, setUploading] = useState(false);
  const [sprint, setSprint] = useState({ name: '', goal: '', startDate: '', endDate: '' });
  const [milestone, setMilestone] = useState({ name: '', description: '', dueDate: '', approvalRequired: false, billableAmount: '' });
  const [member, setMember] = useState({ employeeId: '', role: 'CONTRIBUTOR', allocationPct: '100' });

  const load = useCallback(async () => {
    const [projectResponse, resourceResponse, employeeResponse] = await Promise.all([
      fetch(`/api/projects/${id}`),
      fetch(`/api/projects/${id}/resources`),
      fetch('/api/hr/employees?limit=200'),
    ]);
    const body = await projectResponse.json();
    if (projectResponse.ok) setProject(body.data); else toast.error(body.error);
    if (resourceResponse.ok) setResources((await resourceResponse.json()).data || []);
    if (employeeResponse.ok) { const result = await employeeResponse.json(); setEmployees(result.data || result.items || []); }
  }, [id]);
  useEffect(() => { load(); }, [load]);

  const done = useMemo(() => project?.tasks.filter((task) => task.status === 'DONE').length ?? 0, [project]);
  const progress = project?.tasks.length ? Math.round(done / project.tasks.length * 100) : 0;
  const cost = project?.timesheets.reduce((sum, item) => sum + Number(item.costAmount || 0), 0) || 0;
  const revenue = project?.timesheets.reduce((sum, item) => sum + Number(item.billableAmount || 0), 0) || 0;
  const workflowStatuses = project?.workflowStatuses?.length ? project.workflowStatuses : ['TODO', 'IN_PROGRESS', 'REVIEW', 'DONE'].map((status) => ({ key: status, name: status.replaceAll('_', ' ') }));

  async function post(path: string, body: unknown) {
    const response = await fetch(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
    const result = await response.json();
    if (!response.ok) throw new Error(result.error || 'Request failed');
    await load();
    return result.data;
  }
  async function createSprint() { try { await post('/api/projects/sprints', { projectId: id, ...sprint, startDate: sprint.startDate || null, endDate: sprint.endDate || null }); toast.success('Sprint created'); setSprintOpen(false); setSprint({ name: '', goal: '', startDate: '', endDate: '' }); } catch (error: any) { toast.error(error.message); } }
  async function createMilestone() { try { await post(`/api/projects/${id}/milestones`, { ...milestone, dueDate: milestone.dueDate || null, billableAmount: milestone.billableAmount ? Number(milestone.billableAmount) : null }); toast.success('Milestone created'); setMilestoneOpen(false); } catch (error: any) { toast.error(error.message); } }
  async function addMember() { try { await post(`/api/projects/${id}/members`, { employeeId: member.employeeId, role: member.role, allocationPct: Number(member.allocationPct) }); toast.success('Project member added'); setMemberOpen(false); } catch (error: any) { toast.error(error.message); } }
  async function generateInvoice() { try { await post(`/api/projects/${id}/billing`, {}); toast.success('Draft accounting invoice created'); } catch (error: any) { toast.error(error.message); } }
  async function uploadFile(file?: File) { if (!file) return; setUploading(true); try { const form = new FormData(); form.set('file', file); const response = await fetch(`/api/projects/${id}/attachments`, { method: 'POST', body: form }); const result = await response.json(); if (!response.ok) throw new Error(result.error); toast.success('File uploaded'); await load(); } catch (error: any) { toast.error(error.message); } finally { setUploading(false); } }

  if (!project) return <div className="space-y-4 p-6"><div className="h-24 animate-pulse rounded-md bg-gray-100" /><div className="h-72 animate-pulse rounded-md bg-gray-100" /></div>;
  return <div className="space-y-6 p-6">
    <header><Link href="/projects" className="mb-4 inline-flex items-center text-sm text-gray-500 hover:text-gray-900"><ArrowLeft className="mr-1 h-4 w-4" />Projects</Link><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><Badge variant="outline">{project.code}</Badge><Badge>{project.status.replaceAll('_', ' ')}</Badge><Badge variant="secondary">{project.templateKey.replaceAll('_', ' ')}</Badge><Badge variant="outline">{project.visibility}</Badge></div><h1 className="mt-3 text-3xl font-bold">{project.name}</h1><p className="mt-1 max-w-3xl text-gray-600">{project.description || 'No project description yet.'}</p></div><div className="flex gap-2"><Link href={`/projects/tasks?projectId=${project.id}`}><Button variant="outline"><FolderKanban className="mr-2 h-4 w-4" />Work items</Button></Link><Link href={`/projects/tasks?projectId=${project.id}&create=true`}><Button><Plus className="mr-2 h-4 w-4" />Add work</Button></Link></div></div></header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Progress" value={`${progress}%`} icon={CheckCircle2} /><Metric label="Open work" value={String(project.tasks.length - done)} icon={FolderKanban} /><Metric label="Team" value={String(resources.length)} icon={Users} /><Metric label="Cost" value={`${project.currency} ${cost.toLocaleString()}`} icon={DollarSign} /><Metric label="Margin" value={`${project.currency} ${(revenue - cost).toLocaleString()}`} icon={Activity} /></div>
    {(project.tasks.length === 0 || resources.length <= 1 || project.milestones.length === 0) && <ProjectSetupGuide projectId={project.id} hasWork={project.tasks.length > 0} hasTeam={resources.length > 1} hasMilestones={project.milestones.length > 0} onAddMember={() => setMemberOpen(true)} onAddMilestone={() => setMilestoneOpen(true)} />}
    <Tabs defaultValue="overview"><TabsList className="h-auto w-full justify-start overflow-x-auto p-1"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="list">List</TabsTrigger><TabsTrigger value="timeline">Timeline</TabsTrigger><TabsTrigger value="calendar">Calendar</TabsTrigger><TabsTrigger value="milestones">Milestones</TabsTrigger><TabsTrigger value="sprints">Sprints / Backlog</TabsTrigger><TabsTrigger value="team">Team</TabsTrigger><TabsTrigger value="cost">Time & Cost</TabsTrigger><TabsTrigger value="files">Files</TabsTrigger><TabsTrigger value="activity">Activity</TabsTrigger><TabsTrigger value="settings">Settings</TabsTrigger></TabsList>
      <TabsContent value="overview" className="grid gap-5 pt-3 lg:grid-cols-[1.5fr_1fr]"><Card><CardHeader><CardTitle className="text-base">Delivery health</CardTitle></CardHeader><CardContent><Progress value={progress} /><div className="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">{workflowStatuses.map((status) => <StatusCount key={status.key} status={status.name} count={project.tasks.filter((task) => (task as any).workflowStatusKey === status.key || task.status === status.key).length} />)}</div></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Attention needed</CardTitle></CardHeader><CardContent className="space-y-3"><Signal label="Overdue work" value={project.tasks.filter((task) => task.status !== 'DONE' && task.dueDate && new Date(task.dueDate) < new Date()).length} /><Signal label="Overloaded members" value={resources.filter((item) => item.overloaded).length} /><Signal label="Pending milestones" value={project.milestones.filter((item) => item.approvalStatus === 'PENDING').length} /><Signal label="Draft timesheets" value={project.timesheets.filter((item) => item.approvalStatus === 'DRAFT').length} /></CardContent></Card></TabsContent>
      <TabsContent value="list" className="pt-3"><WorkList tasks={project.tasks} projectId={project.id} /></TabsContent>
      <TabsContent value="timeline" className="pt-3"><Timeline tasks={project.tasks} /></TabsContent>
      <TabsContent value="calendar" className="pt-3"><CalendarView tasks={project.tasks} milestones={project.milestones} /></TabsContent>
      <TabsContent value="milestones" className="space-y-3 pt-3"><div className="flex justify-end"><Dialog open={milestoneOpen} onOpenChange={setMilestoneOpen}><DialogTrigger asChild><Button variant="outline"><Plus className="mr-2 h-4 w-4" />New milestone</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create milestone</DialogTitle></DialogHeader><div className="space-y-3"><Field label="Name"><Input value={milestone.name} onChange={(event) => setMilestone({ ...milestone, name: event.target.value })} /></Field><Field label="Description"><Textarea value={milestone.description} onChange={(event) => setMilestone({ ...milestone, description: event.target.value })} /></Field><Field label="Due date"><Input type="date" value={milestone.dueDate} onChange={(event) => setMilestone({ ...milestone, dueDate: event.target.value })} /></Field><Field label="Billable amount"><Input type="number" min="0" value={milestone.billableAmount} onChange={(event) => setMilestone({ ...milestone, billableAmount: event.target.value })} /></Field><Button className="w-full" onClick={createMilestone} disabled={!milestone.name.trim()}>Create milestone</Button></div></DialogContent></Dialog></div><div className="grid gap-3 md:grid-cols-2">{project.milestones.length ? project.milestones.map((item) => <Card key={item.id}><CardContent className="p-4"><div className="flex items-start justify-between"><CalendarDays className="h-5 w-5 text-blue-600" /><div className="flex gap-1"><Badge variant="outline">{item.status}</Badge><Badge variant="secondary">{item.approvalStatus}</Badge></div></div><p className="mt-3 font-medium">{item.name}</p><p className="text-sm text-gray-500">{item.dueDate ? new Date(item.dueDate).toLocaleDateString() : 'No due date'}{item.billableAmount ? ` · ${project.currency} ${Number(item.billableAmount).toLocaleString()}` : ''}</p></CardContent></Card>) : <Empty text="No milestones configured." />}</div></TabsContent>
      <TabsContent value="sprints" className="space-y-3 pt-3"><div className="flex justify-end"><Dialog open={sprintOpen} onOpenChange={setSprintOpen}><DialogTrigger asChild><Button variant="outline"><Plus className="mr-2 h-4 w-4" />New sprint</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Create sprint</DialogTitle></DialogHeader><div className="space-y-3"><Field label="Name"><Input value={sprint.name} onChange={(event) => setSprint({ ...sprint, name: event.target.value })} /></Field><Field label="Goal"><Textarea value={sprint.goal} onChange={(event) => setSprint({ ...sprint, goal: event.target.value })} /></Field><div className="grid grid-cols-2 gap-3"><Field label="Start"><Input type="date" value={sprint.startDate} onChange={(event) => setSprint({ ...sprint, startDate: event.target.value })} /></Field><Field label="End"><Input type="date" value={sprint.endDate} onChange={(event) => setSprint({ ...sprint, endDate: event.target.value })} /></Field></div><Button className="w-full" onClick={createSprint} disabled={!sprint.name}>Create sprint</Button></div></DialogContent></Dialog></div><div className="grid gap-3 md:grid-cols-2">{project.sprints.map((item) => <Card key={item.id}><CardContent className="p-4"><div className="flex justify-between"><Rocket className="h-5 w-5 text-violet-600" /><Badge variant="outline">{item.status}</Badge></div><p className="mt-3 font-medium">{item.name}</p><p className="text-sm text-gray-500">{item.goal || 'No sprint goal.'}</p><p className="mt-3 text-xs text-gray-500">{project.tasks.filter((task) => task.sprintId === item.id).length} work items</p></CardContent></Card>)}</div></TabsContent>
      <TabsContent value="team" className="space-y-3 pt-3"><div className="flex justify-end"><Dialog open={memberOpen} onOpenChange={setMemberOpen}><DialogTrigger asChild><Button variant="outline"><Plus className="mr-2 h-4 w-4" />Add member</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Add project member</DialogTitle></DialogHeader><div className="space-y-3"><Field label="Employee"><Select value={member.employeeId} onValueChange={(value) => setMember({ ...member, employeeId: value })}><SelectTrigger><SelectValue placeholder="Choose employee" /></SelectTrigger><SelectContent>{employees.map((employee) => <SelectItem key={employee.id} value={employee.id}>{employee.firstName} {employee.lastName}{employee.position ? ` · ${employee.position}` : ''}</SelectItem>)}</SelectContent></Select></Field><Field label="Project role"><Select value={member.role} onValueChange={(value) => setMember({ ...member, role: value })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{['MANAGER', 'CONTRIBUTOR', 'VIEWER', 'TIME_APPROVER'].map((role) => <SelectItem key={role} value={role}>{role.replaceAll('_', ' ')}</SelectItem>)}</SelectContent></Select></Field><Field label="Allocation percentage"><Input type="number" min="0" max="200" value={member.allocationPct} onChange={(event) => setMember({ ...member, allocationPct: event.target.value })} /></Field><Button className="w-full" onClick={addMember} disabled={!member.employeeId}>Add member</Button></div></DialogContent></Dialog></div><Card><CardContent className="divide-y p-0">{resources.length ? resources.map((item) => <div key={item.id} className="grid gap-3 p-4 md:grid-cols-[1fr_130px_130px_130px] md:items-center"><div><p className="font-medium">{item.user?.name || (item.employee ? `${item.employee.firstName} ${item.employee.lastName}` : 'Project member')}</p><p className="text-xs text-gray-500">{item.user?.email || item.employee?.position || item.role}</p></div><Badge variant="outline">{item.role}</Badge><span className="text-sm">{item.allocationPct}% allocated</span><span className={`text-sm font-medium ${item.overloaded ? 'text-red-600' : 'text-emerald-600'}`}>{item.estimatedHours.toFixed(1)}h planned</span></div>) : <Empty text="No project members." />}</CardContent></Card></TabsContent>
      <TabsContent value="cost" className="space-y-4 pt-3"><div className="grid gap-4 md:grid-cols-4"><Metric label="Tracked hours" value={project.timesheets.reduce((sum, item) => sum + Number(item.hours), 0).toFixed(1)} icon={Clock3} /><Metric label="Cost" value={`${project.currency} ${cost.toLocaleString()}`} icon={DollarSign} /><Metric label="Billable value" value={`${project.currency} ${revenue.toLocaleString()}`} icon={DollarSign} /><Metric label="Profitability" value={`${project.currency} ${(revenue - cost).toLocaleString()}`} icon={Activity} /></div><div className="flex justify-end"><Button onClick={generateInvoice} disabled={project.billingType === 'INTERNAL'}>Generate draft invoice</Button></div><Card><CardContent className="divide-y p-0">{project.timesheets.map((entry) => <div key={entry.id} className="grid gap-2 p-4 md:grid-cols-[1fr_100px_130px_130px]"><span>{entry.description || 'Project time'}</span><span>{Number(entry.hours).toFixed(2)}h</span><Badge variant="outline">{entry.approvalStatus}</Badge><span>{entry.billable ? 'Billable' : 'Internal'}</span></div>)}</CardContent></Card></TabsContent>
      <TabsContent value="files" className="space-y-3 pt-3"><div className="flex justify-end"><Button variant="outline" asChild disabled={uploading}><label className="cursor-pointer"><Plus className="mr-2 h-4 w-4" />{uploading ? 'Uploading...' : 'Upload file'}<input className="sr-only" type="file" onChange={(event) => uploadFile(event.target.files?.[0])} /></label></Button></div><Card><CardContent className="divide-y p-0">{project.attachments.length ? project.attachments.map((file) => <a key={file.id} href={file.url} target="_blank" rel="noreferrer" className="flex items-center gap-3 p-4 hover:bg-gray-50"><FileText className="h-5 w-5 text-blue-600" /><div><p className="font-medium">{file.fileName}</p><p className="text-xs text-gray-500">{file.fileType} · {file.fileSize ? `${Math.round(file.fileSize / 1024)} KB` : 'Unknown size'}</p></div></a>) : <Empty text="No project files uploaded." />}</CardContent></Card></TabsContent>
      <TabsContent value="activity" className="pt-3"><Card><CardContent className="divide-y p-0">{project.activities.length ? project.activities.map((item) => <div key={item.id} className="flex gap-3 p-4"><Activity className="mt-0.5 h-4 w-4 text-blue-600" /><div><p className="text-sm font-medium">{item.action.replaceAll('_', ' ')}</p><p className="text-xs text-gray-500">{new Date(item.createdAt).toLocaleString()}</p></div></div>) : <Empty text="No project activity recorded." />}</CardContent></Card></TabsContent>
      <TabsContent value="settings" className="grid gap-5 pt-3 lg:grid-cols-2"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Settings2 className="h-4 w-4" />Project governance</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><Row label="Visibility" value={project.visibility} /><Row label="Template" value={project.templateKey} /><Row label="Billing model" value={project.billingType.replaceAll('_', ' ')} /><Row label="Default billing rate" value={project.defaultBillingRate ? `${project.currency} ${project.defaultBillingRate}` : 'Not set'} /><Row label="Default cost rate" value={project.defaultCostRate ? `${project.currency} ${project.defaultCostRate}` : 'Not set'} /><Row label="Record version" value={String(project.version)} /></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Workflow transitions</CardTitle></CardHeader><CardContent className="space-y-3">{project.workflowStatuses.map((status) => <div key={status.id} className="rounded-md border p-3"><div className="flex items-center justify-between"><span className="font-medium">{status.name}</span><Badge variant="outline">{status.category}</Badge></div><p className="mt-2 text-xs text-gray-500">Can move to: {status.allowedTransitions?.join(', ') || 'No configured transitions'}</p></div>)}</CardContent></Card></TabsContent>
    </Tabs>
  </div>;
}

function Metric({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Clock3 }) { return <Card><CardContent className="flex items-center justify-between p-5"><div className="min-w-0"><p className="text-sm text-gray-500">{label}</p><p className="mt-1 truncate text-xl font-bold">{value}</p></div><Icon className="h-5 w-5 shrink-0 text-blue-600" /></CardContent></Card>; }
function StatusCount({ status, count }: { status: string; count: number }) { return <div className="rounded-md border p-3"><p className="text-xl font-bold">{count}</p><p className="text-xs text-gray-500">{status.replaceAll('_', ' ')}</p></div>; }
function Signal({ label, value }: { label: string; value: number }) { return <div className="flex items-center justify-between rounded-md border p-3"><span className="text-sm">{label}</span><Badge variant={value ? 'destructive' : 'secondary'}>{value}</Badge></div>; }
function WorkList({ tasks, projectId }: { tasks: Task[]; projectId: string }) { return <Card><CardContent className="divide-y p-0">{tasks.length ? tasks.map((task) => <Link key={task.id} href={`/projects/tasks/${task.id}`} className="grid gap-2 p-4 hover:bg-gray-50 md:grid-cols-[1fr_120px_120px] md:items-center"><div><p className="font-medium">{task.title}</p><p className="text-xs text-gray-500">{task.type} · {task.priority}</p></div><Badge variant="outline">{task.status.replaceAll('_', ' ')}</Badge><span className="text-sm text-gray-500">{task.dueDate ? new Date(task.dueDate).toLocaleDateString() : 'No due date'}</span></Link>) : <div className="p-10 text-center"><p className="text-sm text-gray-500">This project has no work yet.</p><Button className="mt-4" asChild><Link href={`/projects/tasks?projectId=${projectId}&create=true`}><Plus className="mr-2 h-4 w-4" />Add first work item</Link></Button></div>}</CardContent></Card>; }
function ProjectSetupGuide({ projectId, hasWork, hasTeam, hasMilestones, onAddMember, onAddMilestone }: { projectId: string; hasWork: boolean; hasTeam: boolean; hasMilestones: boolean; onAddMember: () => void; onAddMilestone: () => void }) {
  const steps = [
    { done: hasWork, title: 'Create the first work item', description: 'Turn the project from a record into executable work.', action: <Button size="sm" asChild><Link href={`/projects/tasks?projectId=${projectId}&create=true`}><Plus className="mr-2 h-4 w-4" />Add work</Link></Button> },
    { done: hasTeam, title: 'Assign the delivery team', description: 'Add contributors, approvers, and workload allocation.', action: <Button size="sm" variant="outline" onClick={onAddMember}><Users className="mr-2 h-4 w-4" />Add member</Button> },
    { done: hasMilestones, title: 'Define a delivery checkpoint', description: 'Add at least one milestone so progress has a business target.', action: <Button size="sm" variant="outline" onClick={onAddMilestone}><CalendarDays className="mr-2 h-4 w-4" />Add milestone</Button> },
  ];
  return <Card className="border-blue-100 bg-blue-50/40"><CardContent className="p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-sm font-semibold text-blue-700">Project setup path</p><h2 className="mt-1 text-lg font-bold">Make this project usable</h2><p className="mt-1 text-sm text-gray-600">Complete these basics so Portfolio, My Work, Work Items, Timeline, and Reports start showing meaningful data.</p></div><Badge variant="outline">{steps.filter((step) => step.done).length}/3 ready</Badge></div><div className="mt-4 grid gap-3 lg:grid-cols-3">{steps.map((step) => <div key={step.title} className="rounded-md border bg-white p-4"><div className="flex items-start gap-3"><CheckCircle2 className={`mt-0.5 h-5 w-5 ${step.done ? 'text-emerald-600' : 'text-gray-300'}`} /><div className="min-w-0 flex-1"><p className="font-medium">{step.title}</p><p className="mt-1 text-sm text-gray-500">{step.description}</p><div className="mt-3">{step.done ? <Badge variant="secondary">Done</Badge> : step.action}</div></div></div></div>)}</div></CardContent></Card>;
}
function Timeline({ tasks }: { tasks: Task[] }) { const dated = tasks.filter((task) => task.startDate || task.dueDate); return <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><GanttChart className="h-4 w-4" />Schedule</CardTitle></CardHeader><CardContent className="space-y-3">{dated.length ? dated.map((task) => <div key={task.id} className="grid gap-2 md:grid-cols-[220px_1fr_130px] md:items-center"><span className="truncate text-sm font-medium">{task.title}</span><div className="h-3 overflow-hidden rounded bg-gray-100"><div className={`h-full ${task.status === 'DONE' ? 'bg-emerald-500' : task.status === 'IN_PROGRESS' ? 'bg-blue-500' : 'bg-gray-400'}`} style={{ width: task.status === 'DONE' ? '100%' : task.status === 'IN_PROGRESS' ? '55%' : '20%' }} /></div><span className="text-xs text-gray-500">{task.dueDate ? new Date(task.dueDate).toLocaleDateString() : 'Unscheduled'}</span></div>) : <Empty text="Add start and due dates to build the project timeline." />}</CardContent></Card>; }
function CalendarView({ tasks, milestones }: { tasks: Task[]; milestones: any[] }) { const events = [...tasks.filter((task) => task.dueDate).map((task) => ({ id: task.id, title: task.title, date: task.dueDate!, type: 'Work item' })), ...milestones.filter((item) => item.dueDate).map((item) => ({ id: item.id, title: item.name, date: item.dueDate, type: 'Milestone' }))].sort((a, b) => +new Date(a.date) - +new Date(b.date)); return <Card><CardContent className="divide-y p-0">{events.length ? events.map((event) => <div key={`${event.type}-${event.id}`} className="grid gap-2 p-4 md:grid-cols-[130px_1fr_120px]"><span className="text-sm font-medium">{new Date(event.date).toLocaleDateString()}</span><span>{event.title}</span><Badge variant="outline">{event.type}</Badge></div>) : <Empty text="No scheduled work or milestones." />}</CardContent></Card>; }
function Empty({ text }: { text: string }) { return <div className="col-span-full p-10 text-center text-sm text-gray-500">{text}</div>; }
function Row({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-3"><span className="text-gray-500">{label}</span><span className="text-right font-medium">{value}</span></div>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>; }
